services:
  backend:
    build:
      context: ./server
    ports:
      - 3001:8080
    volumes:
      - ./server:/server-backend
      - /server-backend/node_modules

  web_frontend:
    build:
      context: ./client-web
    ports:
      - 3000:3000
    volumes:
      - ./client-web:/client-frontend
      - /client-frontend/node_modules
      - /client-frontend/.next
    depends_on:
      - backend

  database:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env

volumes:
  db_data:
