FROM oven/bun:latest

WORKDIR /server-backend

COPY package*.json ./

RUN bun install --production

COPY . .

# Set environment variables
ENV PORT=8080
ENV NODE_ENV=production

# Expose the port that Fly.io expects
EXPOSE 8080

# Start the application in production mode
CMD ["bun", "run", "./src/index.ts"]
