FROM oven/bun:latest

WORKDIR /server-backend

COPY package*.json ./

RUN bun install

COPY . .

# Set environment variables
ENV PORT=8080

# Expose the port that Fly.io expects
EXPOSE 8080

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT [ "docker-entrypoint.sh" ]
