name: Deploy Backend to Fly.io

on:
  push:
    branches: [ main ]  # Change to your primary branch name if needed
    paths:
      - 'server/**'     # Adjust this if your server code is in a different directory

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server  # Adjust this if your server code is in a different directory
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Bun environment
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      # Install dependencies
      - name: Install dependencies
        run: bun install
      
      # Setup Fly.io CLI
      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      # Deploy to Fly.io
      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}